### ISSUE TITLE
API Doc being rendered but not able to click anything

### ISSUE THREAD

**Issue by edgars** [stoplightio/elements#1982] opened 2022-01-19 05:17 UTC
## Describe the bug

Following the basic example to use just element, and nothing else:

```
import React from 'react';

import { API } from '@stoplight/elements';
import '@stoplight/elements/styles.min.css';


function App() {
  return (
    <div className="App">
      <API
        apiDescriptionUrl="https://raw.githubusercontent.com/stoplightio/Public-APIs/master/reference/zoom/openapi.yaml"
      />
    </div>
  );
}

export default App;
```

## To Reproduce

Node version: v16.13.1 

yarn start

The page is not able to click, looks like an image, the lonely message in the log is: 

Failed to load config "@stoplight" to extend from.
Referenced from: /..... /api/elements/.eslintrc.js

## Expected behavior

**Environment (remove any that are not applicable):**
 - Library version: [cloned from github]
 - OS: [MacOS]
 - Browser: [Chrome 61]
 - Platform: [web]

**Comment by mnaumanali94** [comment] 2022-01-19 17:27
Marked urgent unless its a user mistake (Which i highly doubt)

**Comment by jgreen44** [comment] 2022-01-25 20:38
@mnaumanali94 : I'm not able to reproduce

**Comment by mnaumanali94** [comment] 2022-01-25 20:40
@edgars can you help us reproduce please?

**Comment by mpodlasin** [comment] 2022-02-02 17:29
Yeah, it all works for me too. I propose to close it for now.

@edgars if you have more details to help us reproduce, feel free to reopen the issue.

**Closed by mpodlasin** 2022-02-02 17:29 UTC
Labels: t/bug, p/urgent, triaged, team/pierogi-platoon
