### ISSUE TITLE
Why "y is not a function"?

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1396] opened 2021-06-11 14:38 UTC
## Describe the bug

JSV is failing (again).

![Zrzut ekranu 2021-06-11 o 16 32 06](https://user-images.githubusercontent.com/7916523/121702990-a5e31e00-cad2-11eb-9970-1d7904e7b060.png)

## To Reproduce

1. Run react-cra *with published packages*

## Expected behavior

JSV works

**Comment by mmiask** [comment] 2021-06-11 14:41
This is a duplicate of https://github.com/stoplightio/elements/issues/1323

**Closed by mmiask** 2021-06-11 14:41 UTC
Labels: bug, p/high, team/undefined
