### ISSUE TITLE
Markdown links are not rendered properly in header and property descriptions

### ISSUE THREAD

**Issue by savage-alex** [stoplightio/elements#1132] opened 2021-04-26 10:36 UTC
When the description of a header has mark down urls it is not rendered and shown as text instead
![image](https://user-images.githubusercontent.com/25430683/116069511-5e6c1400-a683-11eb-8b11-23722b00bd2c.png)

yaml
responses:
        '200':
          headers:
            RateLimit-Limit:
              type: string
              description: 'The request limit quota for the time window closest to
                exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits)
                for more information.

Example using re-doc
![image](https://user-images.githubusercontent.com/25430683/116069681-93786680-a683-11eb-842d-d7aa9e6f08f6.png)

**Comment by philsturgeon** [comment] 2021-04-26 13:45
Thanks Alex. Duplicate of https://github.com/stoplightio/elements/issues/1092 so please subscribe to that one for updates.

**Closed by philsturgeon** 2021-04-26 13:45 UTC
Labels: bug

**Comment by savage-alex** [comment] 2021-04-26 14:06
Perfect thanks. Sorry to raise a dupe
