### ISSUE TITLE
Errors using React Module in NextJS

### ISSUE THREAD

**Issue by fsargent** [stoplightio/elements#2085] opened 2022-03-31 21:05 UTC
Here are a few errors when I used Elements in Next.js

## Context

Node v14.18.1
"next": "12.0.10",
"@stoplight/elements": "^7.5.13",

## Current Behavior
```
error - Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users//src//website/site/node_modules/@stoplight/http-spec/oas2' is not supported resolving ES modules imported from /Users//src//website/site/node_modules/@stoplight/elements/index.mjs
Did you mean to import @stoplight/http-spec/oas2/index.js?

error - unhandledRejection: SyntaxError: Named export 'saveAs' not found. The requested module 'file-saver' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'file-saver';
const { saveAs } = pkg;
```

## Expected Behavior
No errors

## Possible Workaround/Solution
Will open a ticket with a fix. TLDR:
in `@stoplight/elements/index.mjs`
```
import { saveAs } from 'file-saver';
import { transformOas2Service, transformOas2Operation } from '@stoplight/http-spec/oas2';
import { transformOas3Service, transformOas3Operation } from '@stoplight/http-spec/oas3';
```
to
```
import pkg from 'file-saver';
const { saveAs } = pkg;
import { transformOas2Service, transformOas2Operation } from '@stoplight/http-spec/oas2/index.js';
import { transformOas3Service, transformOas3Operation } from '@stoplight/http-spec/oas3/index.js';
```

**Comment by asimkhan73301** [comment] 2022-04-02 14:09
Any updates on this?
I received the same error after adding the /index.js 

![image](https://user-images.githubusercontent.com/20565471/161387036-00de86a1-1e1e-4b2b-a800-bad17ad74466.png)

**Comment by mnaumanali94** [comment] 2022-04-14 17:11
@fsargent Hey! Thank you for finding this issue and suggesting a fix. Would you still want to make a PR for this? If not, we can go ahead and schedule this.

**Comment by P0lip** [comment] 2022-05-02 13:08
This is a duplicate of https://github.com/stoplightio/elements/issues/1966 and should be fixed now.
LMK in case it's not.

**Closed by P0lip** 2022-05-02 13:08 UTC
Labels: t/bug, p/high
