### ISSUE TITLE
Storybook is empty

### ISSUE THREAD

**Issue by sethsamuel** [stoplightio/elements#2486] opened 2023-12-19 14:11 UTC
After following the instructions in the contributing guide, the storybook for both elements and elements-core is empty.

## Context

Trying to get started with Elements development and while the local demo works, the storybook seems to be missing all components.

## Current Behavior

Storybook is empty.

## Expected Behavior

Storybook should have components for development.

## Steps to Reproduce

1. Clone repo.
2. Run `yarn`.
3. Run `yarn elements storybook`.
4. Load `http://localhost:9001/`.

## Environment

- Version used: Current main branch, commit `04aee60ddfa41e254f25b63d6faa0be6d753cf71`.
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome, node 18.18
- Operating System and version (desktop or mobile): MacOS 14.2, M1
- Link to your environment/workspace/project:

**Comment by chohmann** [comment] 2024-01-05 18:08
@sethsamuel this is duplicate of https://github.com/stoplightio/elements/issues/2493. We are going to close this ticket and work with #2493.

**Closed by chohmann** 2024-01-05 18:08 UTC
